import { EventItem, SearchResult, TodoItem } from "@/types";

export const sampleEvents: EventItem[] = [
  {
    id: "event-1",
    startTime: "2026-04-11T09:32:15",
    endTime: "2026-04-11T10:18:22",
    title: "撰写季度党建汇报材料",
    detail: "整理第一季度重点任务完成情况，补充领导批示摘要。",
    tags: ["党建", "材料"],
    linkedTodoIds: ["todo-1", "todo-3"],
  },
  {
    id: "event-2",
    startTime: "2026-04-11T10:05:00",
    endTime: "2026-04-11T11:06:30",
    title: "核对干部任免表签批流程",
    detail: "与组织部电话确认签批链条，补充送审顺序备注。",
    tags: ["组织", "签批"],
    linkedTodoIds: ["todo-1"],
  },
  {
    id: "event-3",
    startTime: "2026-04-11T10:25:05",
    endTime: "2026-04-11T10:46:30",
    title: "去组织部送盖章文件",
    detail: "外出递交干部任免审批材料，现场核对份数。",
    tags: ["外出", "组织"],
    linkedTodoIds: ["todo-1", "todo-2"],
  },
  {
    id: "event-4",
    startTime: "2026-04-12T14:03:11",
    endTime: "2026-04-12T15:20:45",
    title: "核对编办人员编制台账",
    detail: "逐项核对空编、超编和借调信息。",
    tags: ["编制", "台账"],
  },
  {
    id: "event-5",
    startTime: "2026-04-12T14:20:00",
    endTime: "2026-04-12T14:58:00",
    title: "补录退休人员档案缺项",
    detail: "同步整理退休审批表缺页说明，准备后续复核。",
    tags: ["档案", "补录"],
  },
  {
    id: "event-6",
    startTime: "2026-04-12T16:08:00",
    endTime: "2026-04-12T16:52:18",
    title: "回电宣传部确认先进事迹发布时间",
    detail: "确认推送窗口为本周五，需附一句简短导语。",
    tags: ["宣传", "沟通"],
    linkedTodoIds: ["todo-5"],
  },
  {
    id: "event-7",
    startTime: "2026-04-13T08:40:00",
    endTime: "2026-04-13T09:25:00",
    title: "审核人社局工资审批清单",
    detail: "核对姓名、职级和审批口径，准备回传电子版。",
    tags: ["人社", "审批"],
    linkedTodoIds: ["todo-7"],
  },
  {
    id: "event-8",
    startTime: "2026-04-13T11:10:20",
    endTime: "2026-04-13T12:05:00",
    title: "整理干部档案缺失项",
    detail: "补记学历材料和任免表目录，准备下午联系补件。",
    tags: ["档案", "整理"],
  },
  {
    id: "event-9",
    startTime: "2026-04-13T11:18:00",
    endTime: "2026-04-13T11:52:00",
    title: "补充借调人员台账口径",
    detail: "修正借调期限与在岗状态字段，避免和编办数据冲突。",
    tags: ["台账", "校验"],
  },
  {
    id: "event-10",
    startTime: "2026-04-13T15:30:00",
    endTime: "2026-04-13T17:10:00",
    title: "报送编制调整建议表",
    detail: "根据会议纪要修订说明栏并提交编办。",
    tags: ["编制", "报送"],
    linkedTodoIds: ["todo-4"],
  },
  {
    id: "event-11",
    startTime: "2026-04-13T15:42:00",
    endTime: "2026-04-13T16:18:00",
    title: "电话确认人员信息统计口径",
    detail: "与纪检组核对干部信息表中的现任岗位填写方式。",
    tags: ["纪检", "沟通"],
  },
];

export const sampleTodos: TodoItem[] = [
  {
    id: "todo-1",
    title: "准备职级晋升报审材料",
    dueDate: "2026-04-13T17:30:00",
    priority: "high",
    status: "in_progress",
    tags: ["人事", "材料"],
    department: "组织部",
    contactPerson: "张主任 / 138****1024",
    remarks: "周一上午前送到，需要带公章。",
    parentId: null,
    pinnedToToday: true,
    linkedEventIds: ["event-1", "event-2", "event-3"],
  },
  {
    id: "todo-2",
    title: "整理近三年考核结果附件",
    priority: "medium",
    status: "completed",
    tags: ["附件"],
    parentId: "todo-1",
    linkedEventIds: ["event-3"],
  },
  {
    id: "todo-3",
    title: "补充任职年限证明",
    priority: "high",
    status: "pending",
    tags: ["证明"],
    department: "组织部",
    contactPerson: "王科员",
    remarks: "需同步电子版到工作群。",
    parentId: "todo-1",
    linkedEventIds: ["event-1"],
  },
  {
    id: "todo-6",
    title: "核对任职时间口径",
    priority: "medium",
    status: "pending",
    tags: ["校验"],
    parentId: "todo-3",
  },
  {
    id: "todo-4",
    title: "报送编制调整建议表",
    dueDate: "2026-04-14T11:00:00",
    priority: "medium",
    status: "pending",
    tags: ["编制"],
    department: "编办",
    contactPerson: "刘老师",
    remarks: "会后统一提交扫描件。",
    parentId: null,
    linkedEventIds: ["event-10"],
  },
  {
    id: "todo-5",
    title: "联系宣传部确认先进事迹发布时间",
    dueDate: "2026-04-13T16:00:00",
    priority: "low",
    status: "completed",
    tags: ["宣传"],
    department: "宣传部",
    contactPerson: "赵编辑",
    remarks: "先电话沟通，再发正式稿。",
    parentId: null,
    linkedEventIds: ["event-6"],
  },
  {
    id: "todo-7",
    title: "补发人社局工资审批清单",
    dueDate: "2026-04-13T18:00:00",
    priority: "high",
    status: "pending",
    tags: ["人社", "审批"],
    department: "人社局",
    contactPerson: "李科长",
    remarks: "先传电子版，再纸质报送。",
    parentId: null,
    pinnedToToday: true,
    linkedEventIds: ["event-7"],
  }
];

export const sampleSearchResults: SearchResult[] = [
  {
    id: "result-1",
    kind: "todo",
    title: "准备职级晋升报审材料",
    snippet: "组织部 · 张主任 / 138****1024 · 周一上午前送到，需要带公章。",
    dateLabel: "今天 17:30 截止",
    tags: ["人事", "材料"],
  },
  {
    id: "result-2",
    kind: "event",
    title: "去组织部送盖章文件",
    snippet: "外出递交干部任免审批材料，现场核对份数。",
    dateLabel: "2026-04-11 10:25:05",
    tags: ["外出", "组织"],
  },
  {
    id: "result-3",
    kind: "todo",
    title: "联系宣传部确认先进事迹发布时间",
    snippet: "宣传部 · 赵编辑 · 先电话沟通，再发正式稿。",
    dateLabel: "今天 16:00 截止",
    tags: ["宣传"],
  },
];

export const departmentOptions = ["组织部", "编办", "宣传部", "人社局", "本单位"];
